namespace DeviceExplorer.Resources.Hid
{
    public enum HID_USAGE_GENERIC_DEVICE : ushort
    {
        HID_USAGE_GENERIC_DEVICE_BATTERY_STRENGTH = 0x20,
        HID_USAGE_GENERIC_DEVICE_WIRELESS_CHANNEL = 0x21,
        HID_USAGE_GENERIC_DEVICE_WIRELESS_ID = 0x22,
        HID_USAGE_GENERIC_DEVICE_DISCOVER_WIRELESS_CONTROL = 0x23,
        HID_USAGE_GENERIC_DEVICE_SECURITY_CODE_CHAR_ENTERED = 0x24,
        HID_USAGE_GENERIC_DEVICE_SECURITY_CODE_CHAR_ERASED = 0x25,
        HID_USAGE_GENERIC_DEVICE_SECURITY_CODE_CLEARED = 0x26,
    }
}
