namespace DeviceExplorer.Resources.Hid
{
    public enum HID_USAGE_TELEPHONY : ushort
    {
        HID_USAGE_TELEPHONY_PHONE = 0x01,
        HID_USAGE_TELEPHONY_ANSWERING_MACHINE = 0x02,
        HID_USAGE_TELEPHONY_MESSAGE_CONTROLS = 0x03,
        HID_USAGE_TELEPHONY_HANDSET = 0x04,
        HID_USAGE_TELEPHONY_HEADSET = 0x05,
        HID_USAGE_TELEPHONY_KEYPAD = 0x06,
        HID_USAGE_TELEPHONY_PROGRAMMABLE_BUTTON = 0x07,
        HID_USAGE_TELEPHONY_REDIAL = 0x24,
        HID_USAGE_TELEPHONY_TRANSFER = 0x25,
        HID_USAGE_TELEPHONY_DROP = 0x26,
        HID_USAGE_TELEPHONY_LINE = 0x2A,
        HID_USAGE_TELEPHONY_RING_ENABLE = 0x2D,
        HID_USAGE_TELEPHONY_SEND = 0x31,
        HID_USAGE_TELEPHONY_KEYPAD_0 = 0xB0,
        HID_USAGE_TELEPHONY_KEYPAD_D = 0xBF,
        HID_USAGE_TELEPHONY_HOST_AVAILABLE = 0xF1,
    }
}
