namespace DeviceExplorer.Resources.Hid
{
    public enum HID_USAGE_HAPTICS : ushort
    {
        HID_USAGE_HAPTICS_SIMPLE_CONTROLLER = 0x01,
        HID_USAGE_HAPTICS_WAVEFORM_LIST = 0x10,
        HID_USAGE_HAPTICS_DURATION_LIST = 0x11,
        HID_USAGE_HAPTICS_AUTO_TRIGGER = 0x20,
        HID_USAGE_HAPTICS_MANUAL_TRIGGER = 0x21,
        HID_USAGE_HAPTICS_AUTO_ASSOCIATED_CONTROL = 0x22,
        HID_USAGE_HAPTICS_INTENSITY = 0x23,
        HID_USAGE_HAPTICS_REPEAT_COUNT = 0x24,
        HID_USAGE_HAPTICS_RETRIGGER_PERIOD = 0x25,
        HID_USAGE_HAPTICS_WAVEFORM_VENDOR_PAGE = 0x26,
        HID_USAGE_HAPTICS_WAVEFORM_VENDOR_ID = 0x27,
        HID_USAGE_HAPTICS_WAVEFORM_CUTOFF_TIME = 0x28,
        HID_USAGE_HAPTICS_WAVEFORM_BEGIN = 0x1000,
        HID_USAGE_HAPTICS_WAVEFORM_STOP = 0x1001,
        HID_USAGE_HAPTICS_WAVEFORM_NULL = 0x1002,
        HID_USAGE_HAPTICS_WAVEFORM_CLICK = 0x1003,
        HID_USAGE_HAPTICS_WAVEFORM_BUZZ = 0x1004,
        HID_USAGE_HAPTICS_WAVEFORM_RUMBLE = 0x1005,
        HID_USAGE_HAPTICS_WAVEFORM_PRESS = 0x1006,
        HID_USAGE_HAPTICS_WAVEFORM_RELEASE = 0x1007,
        HID_USAGE_HAPTICS_WAVEFORM_END = 0x1FFF,
        HID_USAGE_HAPTICS_WAVEFORM_VENDOR_BEGIN = 0x2000,
        HID_USAGE_HAPTICS_WAVEFORM_VENDOR_END = 0x2FFF,
    }
}
