namespace DeviceExplorer.Resources.Hid
{
    public enum HID_USAGE_GAME : ushort
    {
        HID_USAGE_GAME_3D_GAME_CONTROLLER = 0x01,
        HID_USAGE_GAME_PINBALL_DEVICE = 0x02,
        HID_USAGE_GAME_GUN_DEVICE = 0x03,
        HID_USAGE_GAME_POINT_OF_VIEW = 0x20,
        HID_USAGE_GAME_GUN_SELECTOR = 0x32,
        HID_USAGE_GAME_GAMEPAD_FIRE_JUMP = 0x37,
        HID_USAGE_GAME_GAMEPAD_TRIGGER = 0x39,
        HID_USAGE_GAME_TURN_RIGHT_LEFT = 0x21,
        HID_USAGE_GAME_PITCH_FORWARD_BACK = 0x22,
        HID_USAGE_GAME_ROLL_RIGHT_LEFT = 0x23,
        HID_USAGE_GAME_MOVE_RIGHT_LEFT = 0x24,
        HID_USAGE_GAME_MOVE_FORWARD_BACK = 0x25,
        HID_USAGE_GAME_MOVE_UP_DOWN = 0x26,
        HID_USAGE_GAME_LEAN_RIGHT_LEFT = 0x27,
        HID_USAGE_GAME_LEAN_FORWARD_BACK = 0x28,
        HID_USAGE_GAME_POV_HEIGHT = 0x29,
        HID_USAGE_GAME_FLIPPER = 0x2A,
        HID_USAGE_GAME_SECONDARY_FLIPPER = 0x2B,
        HID_USAGE_GAME_BUMP = 0x2C,
        HID_USAGE_GAME_NEW_GAME = 0x2D,
        HID_USAGE_GAME_SHOOT_BALL = 0x2E,
        HID_USAGE_GAME_PLAYER = 0x2F,
        HID_USAGE_GAME_GUN_BOLT = 0x30,
        HID_USAGE_GAME_GUN_CLIP = 0x31,
        HID_USAGE_GAME_GUN_SINGLE_SHOT = 0x33,
        HID_USAGE_GAME_GUN_BURST = 0x34,
        HID_USAGE_GAME_GUN_AUTOMATIC = 0x35,
        HID_USAGE_GAME_GUN_SAFETY = 0x36,
    }
}
